version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"  # Adjust the ports as needed
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  # Adjust the ports as needed